const BAD_ENDING_MESSAGES = [
  "KÖTÜ SONU SEÇTİN, EREN KARAYILAN SENİ YİYECEK",
  "KÖTÜ SON, CEHENNEMİ BOYLADIN",
  "KÖTÜ SON, EVİNİ CİNLER BASACAK",
  "KÖTÜ SONA ULAŞTIN, ŞEYTAN SENİ SAĞ KOLU YAPACAK",
  "KÖTÜ SON, EVİNDE YANGIN ÇIKTI YANARAK ÖLDÜN",
  "KÖTÜ SON, KENDİNİ ALEVE VERDİN",
  "KÖTÜ SON, SONSUZA DEK YANACAKSIN",
  "KÖTÜ SON, KADERİNİZİ KABULLENİN, GECE ASLA BİTMEYECEK.",
  "KÖTÜ SON, RUHUNUZ KAYBOLDU, ARTIK ASLA GERİ DÖNMEYECEK.",
  "KÖTÜ SON, YALNIZLIĞIN KARANLIĞINA GÖMÜLDÜNÜZ.",
  "KÖTÜ SON, ZAMANIN DIŞINDA SIKIŞIP KALDINIZ, ÇIKIŞ YOK.",
  "KÖTÜ SON, HER ŞEYİ KAYBETTİNİZ, TEK BAŞINIZA KALDINIZ.",
  "KÖTÜ SON, HAYATINIZ ARTIK SONSUZ BİR KABUS.",
];

const GOOD_ENDING_MESSAGES = [
  "TEBRİKLER, İYİ SONA ULAŞTIN",
  "TEBRİKLER, İKRAMİYE KAZANDIN",
  "TEBRİKLER, EREN KARAYILAN SENİ YEMEĞE DAVET EDİYOR.",
  "TEBRİKLER, KAHRAMAN OLARAK ANILACAKSINIZ.",
  "TEBRİKLER, KAYIP HAZİNEYİ BULUP DÜNYAYI KURTARDINIZ.",
  "TEBRİKLER, BÜTÜN ZORLUKLARIN ÜSTESİNDEN GELDİNİZ, BARIŞ SAĞLANDI.",
  "TEBRİKLER, SIRLARI ÇÖZEREK TARİHE GEÇTİNİZ.",
  "TEBRİKLER, DÜŞMANLARINIZIN ÜSTESİNDEN GELDİNİZ VE ÖZGÜRLÜĞÜ KAZANDINIZ.",
  "TEBRİKLER, GÜVENLİĞE ULAŞTINIZ VE AİLENİZE KAVUŞTUNUZ.",
  "TEBRİKLER, HAYATINIZIN EN BÜYÜK ZAFERİNİ KAZANDINIZ.",
];

const getRandomMessage = (messages: string[]) => {
  return messages[Math.floor(Math.random() * messages.length)];
};

export { BAD_ENDING_MESSAGES, GOOD_ENDING_MESSAGES, getRandomMessage };
